development:
  adapter: redis
  url: <%= ENV['REDIS_URL'] %>
  password: <%= ENV['REDIS_PASSWORD'] %>
  channel_prefix: <%= ENV['REDIS_ENV'] %>

test:
  adapter: redis
  url: <%= ENV['REDIS_URL'] %>
  channel_prefix: <%= ENV['REDIS_ENV'] %>

staging:
  adapter: redis
  url: <%= ENV['REDIS_URL'] %>
  password: <%= ENV['REDIS_PASSWORD'] %>
  channel_prefix: <%= ENV['REDIS_ENV'] %>

production:
  adapter: redis
  url: <%= ENV['REDIS_URL'] %>
  password: <%= ENV['REDIS_PASSWORD'] %>
  channel_prefix: <%= ENV['REDIS_ENV'] %>